database : 
    host : "localhost"
    user : "root"
    password : "a"


RootDirectory : "/data/pilatus1M/data/Cycle_2012_2/"
RelativeLogFileLocation : "/images/livelogfile.log"
ExperimentName : "experiment1"

UserChangePV : "13SIM1:TIFF1:FilePath_RBV"
ImageTakenPV : "13SIM1:cam1:FullFileName_RBV"

