database : 
    host : "localhost"
    user : "root"
    password : "a"


RootDirectory : "/home/dwyerj/beamlinetesting/"
RelativeLogFileLocation : "/raw_dat/livelogfile.log"
ExperimentName : "experiment1"

UserChangePV : "13SIM1:TIFF1:FilePath_RBV"
ImageTakenPV : "13SIM1:cam1:NumImages_RBV"