database : 
    host : "localhost"
    user : "root"
    password : "a"


#These worker always need to be loaded for subtraction and web interface to occur
#WorkerDB will always load
workers : ["WorkerBufferAverage", "WorkerStaticImage", "WorkerRollingAverageSubtraction", "WorkerDB"] 

location : "/home/jack/beamlinetesting/"

UserChangePV : "13SIM1:TIFF1:FilePath_RBV"